---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minecraft-data-oude-stad
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
