---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minecraft-data-maeson-en-papa
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
